// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baitgsfwpvcgebxmhvfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhaXRnc2Z3cHZjZ2VieG1odmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzY2ODYsImV4cCI6MjA1NzU1MjY4Nn0.pILkHtSGqbldlm8VgakkuZSNM93RRYyGPvRNP9hi3I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);